# ########################################################### #
# Pyxel detector simulation framework                         #
#                                                             #
# MARVEL CCD setup for PyEchelle simulations                  #
#                                                             #
# NOTE the following value are from the STA-1600 CCD model.   # 
# Area: 10.3k x 10.3k 9-µm pixels (95 x 95 mm image area)     #
# If not then otherwise stated below. Two read modes exist:   #
#                                                             #
# Fast readout (50 kHz):                                      #
# - Readout noise: 2 e-                                       #
# - 65.8 muV/DN -> 15198 DN/V -> 9.4 e/DN                     #
#                                                             #
# Slow readout (1 MHz):                                       #
# - Readout noise: 5 e-                                       #
# - 21.9 muV/DN -> 45662 DN/V -> 3.0 e/DN                     #
#                                                             #
# ########################################################### #

#--------------------------------------------------------------
exposure:
#--------------------------------------------------------------

  readout:
    non_destructive:  true
    times: '[2.18]'

  outputs:
    output_folder: "output"
    save_data_to_file:
      - detector.image.array: ['fits']

#--------------------------------------------------------------
ccd_detector:
#--------------------------------------------------------------
# NOTE the following value are from the STA-1600 CCD model, and
# if not then otherwise stated below. Two read modes exist:
# Fast readout: 65.8 muV/DN -> 15198 DN/V -> 9.4 e/DN
# Slow readout: 21.9 muV/DN -> 45662 DN/V -> 3.0 e/DN

  geometry:

    row: 10560              # [pixel]
    col: 10560              # [pixel]
    total_thickness: 40.    # [um] -> pyxel default
    pixel_vert_size: 9.     # [um]
    pixel_horz_size: 9.     # [um]

  material:
    material: 'silicon'

  environment:
    temperature: 200        # [K]

  characteristics:
    quantum_efficiency:        0.9         # QE approximation
    charge_to_volt_conversion: 7.0e-6      # [V/e] Charge readout sensitivity
    pre_amplification:         16          # [V/V] Gain of output amplifier
    adc_voltage_range:         [0., 16.]   # [V] Output DC Level
    adc_bit_resolution:        16
    full_well_capacity:        800000      # [e] Full-well capacity

#--------------------------------------------------------------
pipeline:
#--------------------------------------------------------------

  # photon -> photon
  photon_generation:
  
    - name: shot_noise
      func: pyxel.models.photon_generation.shot_noise
      enabled: true

    - name: cosmix
      func: pyxel.models.charge_generation.cosmix
      enabled: true
      arguments:
        simulation_mode: cosmic_ray
        running_mode: stepsize
        particle_type: proton
        initial_energy: 100.       # [MeV]
        particles_per_second: 100  # [p/s]
        incident_angles:
        starting_position:
        spectrum_file: "inputfiles/proton_L2_solarMax_11mm_Shielding.txt"
        seed: 4321

  # photon -> charge
  charge_generation:

    # Load in PyEchelle image
    - name: load_charge
      func: pyxel.models.charge_generation.load_charge
      enabled: true
      arguments:
        filename: science_0001.fits  # NOTE will be overwritten
        position: [0,0]
        align: "center"
        time_scale: 1            # NOTE will be overwritten

    - name: dark_current
      func: pyxel.models.charge_generation.dark_current
      enabled: true
      arguments:
        dark_rate: 0.1   # [e/pix/s] TODO this should be provided by manufacturer


  # charge -> pixel
  charge_collection:

    # NOTE this simple module is always needed!
    - name: simple_collection
      func: pyxel.models.charge_collection.simple_collection
      enabled: true

    - name: full_well
      func: pyxel.models.charge_collection.simple_full_well
      enabled: true

    - name: simple_persistence
      func: pyxel.models.charge_collection.simple_persistence
      enabled: false
      arguments: # TODO configure!
        trap_timeconstants: [1., 10.]    # Two traps
        trap_densities: [0.307, 0.175]

  # pixel -> pixel
  charge_transfer:
    - name: cdm
      func: pyxel.models.charge_transfer.cdm
      enabled: false
      arguments:
        direction: parallel
        trap_release_times: [3.e-2]
        trap_densities: [20.]
        sigma: [1.e-10]
        beta: 0.1
        max_electron_volume: 1.62e-10   # [cm^2]
        transfer_period: 9.4722e-04     # [s]
        charge_injection: false

  # pixel -> signal
  charge_measurement:

    - name: simple_measurement
      func: pyxel.models.charge_measurement.simple_measurement
      enabled: true

  # signal -> image
  readout_electronics:

    - name: simple_amplifier
      func: pyxel.models.readout_electronics.simple_amplifier
      enabled: true
      
    - name: simple_adc
      func: pyxel.models.readout_electronics.simple_adc
      enabled: true
