#!/bin/bash

#PBS -N output
#PBS -A <account>
#PBS -l nodes=1:ppn=14:gpus=4:skylake
#PBS -l pmem=30gb
#PBS -l walltime=04:00:00

cd $PBS_O_WORKDIR

# Export paths
POETRY=$VSC_DATA/poetry/virtualenvs/marvelsim-3qcQCF7a-py3.8/bin/activate
export POETRY
SIMDIR=$VSC_DATA/marvelsim/marvelsim
export SIMDIR
OUTDIR=/scratch/leuven/341/vsc34166/marvelsim/output
export OUTDIR

# Activate poetry shell
source $POETRY

# Run star spectrum
python $SIMDIR/marvel.py -s --time 300 --dex $index --zip -o $OUTDIR
