#!/bin/bash

#PBS -N output
#PBS -A <account_name>
#PBS -l nodes=1:ppn=36:gpus=4:skylake
#PBS -l partition=gpu
#PBS -l pmem=2gb
#PBS -l walltime=03:00:00

cd $PBS_O_WORKDIR

PYTHONPATH=$VSC_DATA/MARVELsim/marvelsim/bin/python
export PYTHONPATH
SIMDIR=$VSC_DATA/MARVELsim
export SIMDIR

# Activate environment
source marvelsim/bin/activate

# Run MARVELsim
cd $SIMDIR
python simulator-marvel.py --calibs --cuda --zip -o $SIMDIR/output
