#!/bin/bash

#PBS -N output
#PBS -A lp_mesa_modeling
#PBS -l nodes=1:ppn=36:gpus=4:cascadelake
#PBS -l partition=gpu
#PBS -l pmem=2gb
#PBS -l walltime=00:10:00
#PBS -l qos=debugging

cd $PBS_O_WORKDIR

PYTHONPATH=$VSC_DATA/MARVELsim/marvelsim/bin/python
export PYTHONPATH
SIMDIR=$VSC_DATA/MARVELsim
export SIMDIR
OUTDIR=$VSC_SCRATCH/marvelsim/test
export $OUTDIR

# Make sure to activate environment 
source marvelsim/bin/activate

# Run star spectrum
cd $SIMDIR
python simulator-marvel.py --time 900 --rv 1000 --cuda --zip -o $SIMDIR/output


