#!/bin/bash

#PBS -N output
#PBS -A lp_mesa_modeling
#PBS -l nodes=1:ppn=14:gpus=4:skylake
#PBS -l partition=gpu
#PBS -l pmem=2gb
#PBS -l walltime=06:00:00

cd $PBS_O_WORKDIR

# Export paths
SIMDIR=$VSC_DATA/marvelsim/marvelsim
export SIMDIR
OUTDIR=</path/to/output/>
export OUTDIR
POETRY=</path/to/poetry/virtualenvs/name>

# Run calibration
. $POETRY
python $SIMDIR/marvelsim.py --time 900 --mag 10.0 --teff 5800 --logg 4.5 --z 0.0 --alpha 0.0 --cuda --data data.txt -o $OUTDIR

